# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e933a4e30773f93bd1def27c902b908835f4253a5066c6228c1519953f78a70b660586fca3755c1088afafd7066dd9169c1d0b08401062d58b93c71e71b34135

test:
  secret_key_base: ec8536adac69422fd9e89cae0a8ae4b43b0d5fbfc396dd60f4874f128d28cd2588b42ed119360dc9132662e94e19b034f5ee6ab381acebecffbbf0a8eff36704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
