Category.create(name: 'PASTRIES')
Category.create(name: 'BREADS')
Category.create(name: 'CAKES')
Category.create(name: 'PIES')
Category.create(name: 'BARS')
Category.create(name: 'COOKIES')
Category.create(name: 'OTHERS')
